#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Vipulasri.TimelineView.Resource", IsApplication=false)]

namespace Vipulasri.TimelineView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int line = 2130771969;
			
			// aapt resource value: 0x7f010004
			public static int lineOrientation = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int linePadding = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int lineSize = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int marker = 2130771968;
			
			// aapt resource value: 0x7f010006
			public static int markerInCenter = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int markerSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int marker = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int vertical = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] timeline_style = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public static int timeline_style_line = 1;
			
			// aapt resource value: 4
			public static int timeline_style_lineOrientation = 4;
			
			// aapt resource value: 5
			public static int timeline_style_linePadding = 5;
			
			// aapt resource value: 3
			public static int timeline_style_lineSize = 3;
			
			// aapt resource value: 0
			public static int timeline_style_marker = 0;
			
			// aapt resource value: 6
			public static int timeline_style_markerInCenter = 6;
			
			// aapt resource value: 2
			public static int timeline_style_markerSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
